










export const metadata = {
    title: "Services",
    description: "Generated by create next app",
};
const ServicesPage =()=>{
    return(
        <>
            <div>
                <h1>Services Page</h1>
            </div>
        </>
    )
}


export default ServicesPage;